[CB-555] 상품 상세페이지 디자인 적용
PinkDumbbell/CocoBob-FE pull request #106
Opened 2022-11-22 13:15 UTC by dmstmdrbs

[CB-555]

### 🔨 Jira 태스크

- [CB-556] 상품 리스트 디자인 리뉴얼
- [CB-557] 상품 상세페이지 레이아웃 쉬프트 방지가 필요함

### 📐 구현한 내용

- 전체적인 스타일 구조를 변경하였습니다. 
- 새로운 스타일을 적용했습니다!
  - 이제 브랜드명이 짤리는 일은 없을거에요!
    <img src='https://user-images.githubusercontent.com/2215762/203322175-764a932a-7a8f-4334-8b12-49c95800a886.png' width='240' />

### 🚧 논의 사항

- 불필요한 스타일 요소들이 조금 남아있는 것 같지만, 대부분 매끄럽게 재구성 해보았습니다.
- 추후에 styled-components를 tailwind로 리팩토링 해보는 것도 좋을 것 같네요

2022-11-22 15:30 UTC, taehong0-0 approved these changes
고생하셨습니다 !

2022-11-22 17:39 UTC, Wisesaturn requested changes
고생하셨어요!
상품 상세 페이지 하단 부분에 정렬이 필요할 것 같아요!
branch `pr/106`에 간단하게 해보았습니다.

2022-11-22 18:33 UTC, Wisesaturn requested changes
추가로 다시 검토해보았습니다!

2022-11-22 18:33 UTC, Wisesaturn commented on src/pages/Products/ProductDetail.tsx
> +              <h2 className="text-primary">충족</h2>
**AFFCO**에 따라 상품 상세가 반영이 되지 않는 듯 합니다!

```
{product?.isAAFCOSatisfied && <h2 className="mb-[15px] text-primary">충족</h2>}
{!product?.isAAFCOSatisfied && <h2 className="mb-[15px] text-bad">부적합</h2>}
```
**product AAFCO 조건**을 가져와서 추가해보았습니다.

2022-11-23 07:57 UTC, dmstmdrbs commented
> 고생하셨어요! 상품 상세 페이지 하단 부분에 정렬이 필요할 것 같아요! branch `pr/106`에 간단하게 해보았습니다.

PR올려주세요!

2022-11-23 09:05 UTC, dmstmdrbs commented on src/pages/Products/ProductDetail.tsx
> +              <h2 className="text-primary">충족</h2>
이 부분 다음 PR에서 리팩토링 해보겠습니다!
대대적인 수정이 필요해보이네요 ㅎㅎ

2022-11-23 10:11 UTC, merged