[CB-559] 상품 목록 페이지 스타일 수정
PinkDumbbell/CocoBob-FE pull request #107
Opened 2022-11-22 14:55 UTC by dmstmdrbs

[CB-559]

### 🔨 Jira 태스크

-

### 📐 구현한 내용

- 상품 목록 메뉴 & 상품 목록 아이템 스타일 수정
  <img src='https://user-images.githubusercontent.com/2215762/203345712-f32251fc-649c-4788-9a75-20cd601d038e.png' width='250'/>
- 상품 목록 페이지 헤더 검색 버튼 위치 조정
  - 이제 다른 페이지의 버튼 위치와 동일합니다!

### 🚧 논의 사항

-

[CB-559]: https://cocobob.atlassian.net/browse/CB-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-11-22 15:37 UTC, taehong0-0 approved these changes
고생하셨습니다 !

2022-11-22 15:37 UTC, taehong0-0 commented on src/pages/Products/components/CategoryTabs.tsx
> +        <CategoryTab
이 부분은 배열에 넣어두고 map을 사용해보는 건 어떨까요? 나중에 추가할 때도 편할 것 같아요

2022-11-22 18:37 UTC, Wisesaturn requested changes
고생하셨습니다!
간단한 스타일 변경만 하면 될 것 같습니다!

---

#### 적용한다면
`:before` Pseudo element에 의해 **Loading Components** 위에 스타일이 적용이 됩니다
로딩스피너의 z-index를 적당하게 높여줄 필요가 있어 보입니다!

2022-11-22 18:37 UTC, Wisesaturn commented on src/components/Product/index.tsx
> +            <p className="text-primary-dark text-label font-medium">AAFCO 충족</p>
`className`에
`relative after:rounded after:block after:absolute after:left-0 after:opacity-25 after:top-2.5 after:bg-primary-brightest after:py-1.5 after:px-9` 한번 스타일 추가해주시면 감사하겠습니다!
뒷 형광색으로 강조한 느낌의 스타일입니다!

2022-11-22 18:37 UTC, Wisesaturn commented on src/components/Product/index.tsx
> +            <p className="text-gray text-label font-medium">AAFCO 미달</p>
여기도
`relative after:rounded after:block after:absolute after:left-0 after:opacity-25 after:top-2.5 after:bg-secondary-brighter after:py-1.5 after:px-9` 넣어서 확인해주시면 감사하겠습니다!

2022-11-22 18:37 UTC, Wisesaturn commented on src/components/Product/index.tsx
> +  return <p className="text-gray">노령견</p>;
노령견 -> 성견으로 바꿔야 할 듯 합니다!

2022-11-22 18:37 UTC, Wisesaturn commented on src/pages/Products/components/Submenus.tsx
> +    <div className="bg-primary-lightdark w-full px-3 flex items-center justify-between rounded-b overflow-hidden">
`bg-primary-max`로 변경해서 흰색으로 수정하는게 더 시선분산이 덜 할듯 합니다!

2022-11-22 18:37 UTC, Wisesaturn commented on src/pages/Products/components/Submenus.tsx
> +            className="border w-20 h-full flex items-center gap-1 text-xs justify-center border-none text-white"
`text-white`를 지운 후
`text-black font-semibold before:block before:relative before:border-l-2 before:left-0 before:border-secondary-brighter before:pl-3.5 before:h-4` 스타일 추가해서 확인해주시면 감사하겠습니다!

2022-11-22 18:37 UTC, Wisesaturn commented on src/pages/Products/components/Submenus.tsx
> +          className="rounded-sm text-white w-14 h-full flex items-center gap-1 text-xs justify-center"
`text-white`를 지운 후 `text-black font-semibold` 추가해주시면 감사하겠습니다!

2022-11-23 07:12 UTC, dmstmdrbs commented on src/pages/Products/components/CategoryTabs.tsx
> +        <CategoryTab
음 저는 저희 기획에서는 최대 3개 메뉴 밖에 없어서 풀어서 쓰는 것도 괜찮다고 생각했습니다!

2022-11-23 07:15 UTC, dmstmdrbs commented on src/components/Product/index.tsx
> +            <p className="text-primary-dark text-label font-medium">AAFCO 충족</p>
앗 친절하게 스타일 전부 주셨군요 ㅠㅠ 감사합니다

2022-11-23 07:16 UTC, dmstmdrbs commented on src/components/Product/index.tsx
> +            <p className="text-gray text-label font-medium">AAFCO 미달</p>
넵 감사합니다!

2022-11-23 07:16 UTC, dmstmdrbs commented on src/components/Product/index.tsx
> +  return <p className="text-gray">노령견</p>;
앗 이 부분을 놓쳤었네요! 수정했습니다

2022-11-23 07:23 UTC, dmstmdrbs commented on src/pages/Products/components/Submenus.tsx
> +            className="border w-20 h-full flex items-center gap-1 text-xs justify-center border-none text-white"
<img width="414" alt="image" src="https://user-images.githubusercontent.com/2215762/203491270-a0d41d13-62cc-4965-b15e-aecfa96edaf9.png">

이런 느낌이 맞을까요?
스타일은 좋은 것같습니다! 
근데 이렇게 하면 border-left 부분도 버튼이 되어버려서 | 부분에도 초기화 버튼 동작이 적용되어버혀서, 버튼과 분리하는게 더 나을 것 같습니다!

2022-11-23 07:38 UTC, dmstmdrbs commented on src/pages/Products/components/Submenus.tsx
> +            className="border w-20 h-full flex items-center gap-1 text-xs justify-center border-none text-white"
같은 스타일로 Divider를 따로 두어 추가하였습니다!

2022-11-23 07:47 UTC, dmstmdrbs commented
@Wisesaturn 스타일 지적해주신 부분 수정했습니다 확인 부탁드려요!

2022-11-23 07:54 UTC, Wisesaturn approved these changes
스타일 확인했습니다! 고생하셨어요!

2022-11-23 09:03 UTC, merged